// using System;
// using System.Windows;
// using Avalonia;
// using Avalonia.Controls;
// using Avalonia.Media;
// using FontAwesome.Generate;

// namespace FontAwesome.Avalonia
// {
//     [IconGenerate]
//     public class AutogeneratedIcons
//     {
        
//     }
// }
